# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - NoroffAlumni

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://alumniregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d769f94c685140079a57aa4993ba50e2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_db866c4f22b648f9bc0bee59535b8f67 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: alumniregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d769f94c685140079a57aa4993ba50e2 }}/alumniapi:${{ github.sha }}
        file: ./AlumniNetworkApi/Dockerfile 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NoroffAlumni'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c5c3797bdca04a29bb4c320164f40b5d }}
        images: 'alumniregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d769f94c685140079a57aa4993ba50e2 }}/alumniapi:${{ github.sha }}'
